spring:
  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true

  data:
    mongodb:
      host: localhost
      port: 27017
      database: awesomeMongo

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

mongock:
  change-logs-scan-package: ru.otus.spring.changelogs
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"