apiVersion: v1
kind: Service
metadata:
  name: docker-service-book-library-test-client-service
spec:
  type: NodePort
  selector:
    app: docker-service-book-library-test-client
  ports:
    - name: "client"
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083