apiVersion: v1
kind: Service
metadata:
  name: docker-service-discovery-server
spec:
  type: NodePort
  selector:
    app: docker-service-discovery-server
  ports:
    - name: "discovery"
      protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30761