apiVersion: v1
kind: Service
metadata:
  name: docker-service-book-library
spec:
  type: NodePort
  selector:
    app: docker-service-book-library
  ports:
    - name: "library"
      protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082